export enum DashboardStepEnum {
    ASSET_CLUSTERING = <any> 'ASSET_CLUSTERING',
    IDENTIFY_THREAT_AGENTS = <any> 'IDENTIFY_THREAT_AGENTS',
    ASSESS_VULNERABILITIES = <any> 'ASSESS_VULNERABILITIES',
    REFINE_VULNERABILITIES = <any> 'REFINE_VULNERABILITIES',
    IMPACT_EVALUATION = <any> 'IMPACT_EVALUATION',
    RISK_EVALUATION = <any> 'RISK_EVALUATION'
}
