package eu.hermeneut.domain.dashboard;

public enum DashboardStep {
    ASSET_CLUSTERING,
    IDENTIFY_THREAT_AGENTS,
    ASSESS_VULNERABILITIES,
    REFINE_VULNERABILITIES,
    IMPACT_EVALUATION,
    RISK_EVALUATION,
    ATTACK_RELATED_COSTS
}
