package eu.hermeneut.domain.enumeration;

/**
 * The CompType enumeration.
 */
public enum CompType {
    INFORMATION, HEALTHCARE, FINANCE, ACCOMODATION, ADMINISTRATIVE, AGRICOLTURE, CONSTRUCTION, EDUCATION, ENTERTAINMENT, MANAGEMENT, MANUFACTURING, MINING, OTHERSERVICES, PROFESSIONAL, PUBLIC, REALESTATE, RETAILS, TRADE, TRANSPORTATION, UTILITIES
}
