package eu.hermeneut.domain.enumeration;

/**
 * The ThreatArea enumeration.
 */
public enum ThreatArea {
    NETWORK_AND_TECHNICAL_RESOURCES, PROCEDURES_RELATED_TO_THE_PROCESSING_OF_PERSONAL_DATA, PEOPLE_INVOLVED_IN_THE_PROCESSING_OF_PERSONAL_DATA, BUSINESS_SECTOR_AND_SCALE_OF_PROCESSING
}
